##########################################
#                                        #
#      Settings and configuration        #
#                                        #
##########################################

# Due to MySQL integer (number) limitations, the maximum amount a number should be is '2147483647'.
# '1073741823' should be the maximum number you put in these settings. (unless you know what you are doing)
# Keep in mind decimals will not work. MySQL rounds them up.

website:
  port: 7878 # The port you want Dashactyl to run on.
  secret: "SuPeRsEcUrEpAsSwOrD" # Make this very secure and complicated. (Up to 32 characters)

  title: "Betteractyl - a better fork of Dashactyl" # 
  description: "Free Game Hosting - Get started now with 1GB RAM, unlimited players, unlimited plugins, 24/7 up, no queues! Support for Minecraft, Discord Bots and more!" # The description that will appear when shared on social medias such as discord
  color: "#00FFFF" # The color of the embed that will appear when shared on social medias such as discord
  link: "https://discord.gg/McFr2jwNSE" # Used for frontend purposes / a link to your site
  favicon: "./assets/images/favicon.png" # The favicon of the website (use './assets/images/favicon.png' for local OR 'https://link.to/favicon.png' for hosted)
  banner: "https://media.discordapp.net/attachments/606866047987089437/975458101106991114/navbar-cover.jpg?width=626&height=206" # The banner that will appear when shared on social medias such as discord

##########################################
#                                        #
#           API Credentials              #
#                                        #
##########################################

discord:
  id: "Application ID" # The ID of your discord application
  secret: "Application Secret" # The secret of your discord application
  callbackpath: "http://127.0.0.1:7878/accounts/callback" # Your callback path. (https://<DOMAIN>/accounts/callback) | DONT FORGET TO ADD IT AS A REDIRECT URI IN THE DISCORD DEVELOPER PORTAL
  prompt: false
  
  token: "Bot Token" # The token of your bot
  guild: "971081978541658122" # Add the ID of the guild that you want to force the users in when they login
  roles: ["971081978541658129"] # Add the IDs of the role you want to be granted when logging into the dashboard.

pterodactyl:
  domain: "https://panel.acktar.dev" # Direct link to your pterodactyl panel
  key: "EoLoPc59FLkaUnncsccecMQxxlWRxjxRrCKGwNxivtoEjRgC" # Make sure to higher/remove rate limits for application API keys, so the dashboard doesn't get rate limited.
  generate_password_on_sign_up: true # If set to false the users will have to generate a new password via the Regenerate password button

database: # MySQL database.
  host: "192.168.100.1" # URL/IP to connect to your mysql database
  port: "3306" # Port to connect on! Default is 3306
  user: "acktr" # Username to connect with!
  password: "Async!" # Password to connect with!
  database: "betteractyl" # Name of your database which Betteractyl will use!

auditlogs: # This feature enable auditlogs for dashactyl v1
  enabled: true # enable or disable the Audit Logs
  webhook_url: https://discord.com/api/webhooks/963711634528940052/KOHN1Ju3LDwNfdgtUaD2HG4mn-k4Hgk6HnOqPyhcnyPaX_8Gp2riZE8SVN-hx8TA7SYC" 

email_system: # This feature enable email system for Dashactyl v1
  enabled: false # enable or disable the email system
  smtp_host: "smtp.yandex.com.tr" # You need to put here your smtp host from your email software (gmail, zoho, etc.) like smtp.zoho.com
  smtp_port: "465" # Put the port of your smtp host like 465
  smtp_user: "fake@acktar.dev" # Your email like nohaxito@mydomain.gg
  smtp_password: "hehehSUIIIII" # Your email password.
  extra: # Some additional things, this will edit some links in the HTML format that will be sent by email
    dashboardurl: "https://acktar.dev" # Necessary
    dashboardname: "My Dashboard" # Necessary

api: # The client area might break if there are no API codes, so I highly recommend adding a single secure API code.
  SuPeRsEcUrEpAsSwOrDbYaCkTaR: # This would be the "Bearer apicodepassword".
    user info: true
    blacklist user: true
    unblacklist user: true
    set coins: true
    set package: true
    set resources: true
    create coupon: true
    revoke coupon: true

##########################################
#                                        #
#        Nodes and Eggs Setup            #
#                                        #
##########################################
locations:
  "1": # Location ID from pterodactyl.
    name: "Free-1" # Location display name.
    enabled: true # Enable or disable server creation on this location.
    package: 
    - default # Required package to make a server on this location.
    - pro # other premium packages.

    renewal: true # Enables renewals for this feature. (Do not toggle after setting up this node on the client area. It might break things.)
 
  "2": # Location ID from pterodactyl.
    name: "Donator-1" # Location display name.
    enabled: true # Enable or disable server creation on this location.
    package: 
    - pro # premium packages only.

    renewal: true # Enables renewals for this feature. (Do not toggle after setting up this node on the client area. It might break things.)

eggs: # These are the eggs servers can be created with.
  paper:
    display: "Paper"
    minimum:
      memory: 100
      disk: 100
      cpu: 10
    maximum:
      memory: null
      disk: null
      cpu: null
    info:
      egg: 3
      docker_image: quay.io/pterodactyl/core:java
      startup: java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}
      environment:
        SERVER_JARFILE: "server.jar"
        BUILD_NUMBER: "latest"
      feature_limits:
        databases: 1
        backups: 1

packages: # These are packages. They are organized categories on how much resources you would give to anyone with this package.
  default: "default"
  list:
    default:
      display: "Free user"
      memory: 1024
      disk: 5000
      cpu: 100
      servers: 1
    pro:
      display: "Pro Package"
      memory: 2048
      disk: 2048
      cpu: 200
      servers: 2

store: # This is the store options.
  # 'enabled' is an option, which toggles if you can buy a single type of resource of.
  # 'cost' is the amount of coins 'per' of a resource would cost.

  memory:
    enabled: true
    cost: 2000
    per: 1024

  disk:
    enabled: true
    cost: 2000
    per: 1024

  cpu:
    enabled: true
    cost: 5000
    per: 10

  servers:
    enabled: true
    cost: 150
    per: 1

afk:
  domain_lock:
    - localhost:7878 # Change this to your actual domain.
  redirect_on_attempt_to_steal_code: https://www.youtube.com/watch?v=dQw4w9WgXcQ

  everywhat: 60 # seconds
  gaincoins: 1 # coins
  arc_id: "EURdXiDJ" # your arc widget id without the '#'
renewal:
  renewal_time: 6.048e+8
  deletion_time: 8.64e+7

  renew_fee: 10 # coins
